services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: realmate
      POSTGRES_USER: realmate
      POSTGRES_PASSWORD: realmate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-back
    command: poetry run python manage.py runserver 0.0.0.0:80
    volumes:
      - ./backend:/app
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-front
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8000:5173"

volumes:
  postgres_data:
